# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2eae8f7e658662a6e9e0ff6fd69578b8bd35acd06f6d02e6586544dc1729f9c618f9bba9e6e392e722b6111e6233f3d7c26d84db8c4bf7983bfdf82e337c3e0

test:
  secret_key_base: add4db5fa980cc6bbd621e5c9692d58d4822d88280133ad88ebbded3a6bba4d120e74f993a266c7e07371bcbb21e55e00360d60ee91b2b52a520257bd382bf65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
